# Trankuil Jetpack Compose Version Catalog
# Android Jetpack Compose libraries
[versions]
coil = "2.7.0"
compose-bom = "2025.12.01"
compose-compiler = "1.5.15"

[libraries]
# Foundation
animation = { module = "androidx.compose.animation:animation" }
animation-core = { module = "androidx.compose.animation:animation-core" }
animation-graphics = { module = "androidx.compose.animation:animation-graphics" }
# BOM
bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
# Coil (Compose image loading)
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }
foundation = { module = "androidx.compose.foundation:foundation" }
foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
# Material (legacy)
material = { module = "androidx.compose.material:material" }
material-icons-core = { module = "androidx.compose.material:material-icons-core" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
# Material3
material3 = { module = "androidx.compose.material3:material3" }
material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
material3-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout" }
material3-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation" }
material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }
# Runtime
runtime = { module = "androidx.compose.runtime:runtime" }
runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable" }
# UI
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-text = { module = "androidx.compose.ui:ui-text" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
ui-util = { module = "androidx.compose.ui:ui-util" }
ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }

[bundles]
coil = [
    "coil",
    "coil-gif",
    "coil-svg",
]
core = [
    "foundation",
    "runtime",
    "ui",
    "ui-graphics",
    "ui-tooling-preview",
]
material3 = [
    "material-icons-core",
    "material3",
]
material3-adaptive = [
    "material3-adaptive",
    "material3-adaptive-layout",
    "material3-adaptive-navigation",
]
testing = [
    "ui-test-junit4",
    "ui-test-manifest",
]
tooling = [
    "ui-tooling",
    "ui-tooling-preview",
]
