# Trankuil Utils Version Catalog
[versions]
# Arrow
arrow = "2.2.1.1"
# Code Quality
detekt = "1.23.8"
dependency-guard = "0.5.0"
dokka = "2.1.0"
exposed = "0.61.0"
# Testing
junit5 = "6.0.1"
kotest = "6.0.7"
ktlint = "1.4.1"
# Networking
ktor = "3.3.3"
# Debugging
leakcanary = "2.14"
konsist = "0.17.3"
# Logging
log4k = "1.2.3"
logback = "1.5.23"
maven-publish = "0.35.0"
mockk = "1.14.7"
okhttp = "5.3.2"
slf4j = "2.0.17"
spotless = "8.1.0"
# Database
sqldelight = "2.2.1"
turbine = "1.2.1"

[libraries]
# Arrow
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
arrow-optics = { module = "io.arrow-kt:arrow-optics", version.ref = "arrow" }
arrow-optics-ksp = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrow" }
# Exposed
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
# Testing
junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
# Ktor Client
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
# Ktor Server
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
# Debugging
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
# Gradle Plugins
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-dependency-guard = { module = "com.dropbox.dependency-guard:dependency-guard", version.ref = "dependency-guard" }
gradle-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradle-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }
gradle-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
# Logging
log4k = { module = "io.github.smyrgeorge:log4k", version.ref = "log4k" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
# OkHttp
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
# SQLDelight
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-paging = { module = "app.cash.sqldelight:androidx-paging3-extensions", version.ref = "sqldelight" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }

[bundles]
arrow = [
    "arrow-core",
    "arrow-fx-coroutines",
]
exposed = [
    "exposed-core",
    "exposed-dao",
    "exposed-jdbc",
    "exposed-kotlin-datetime",
]
kotest = [
    "kotest-assertions",
    "kotest-property",
    "kotest-runner",
]
ktor-client-android = [
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-client-logging",
    "ktor-client-okhttp",
    "ktor-serialization-json",
]
ktor-client-ios = [
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-client-darwin",
    "ktor-serialization-json",
]
ktor-client-jvm = [
    "ktor-client-cio",
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-client-logging",
    "ktor-serialization-json",
]
ktor-server = [
    "ktor-serialization-json",
    "ktor-server-call-logging",
    "ktor-server-content-negotiation",
    "ktor-server-core",
    "ktor-server-netty",
]
logging-jvm = [
    "logback",
    "slf4j-api",
]
logging-multiplatform = [
    "log4k",
]
okhttp = [
    "okhttp",
    "okhttp-logging",
]
sqldelight-common = [
    "sqldelight-coroutines",
    "sqldelight-runtime",
]
testing-android = [
    "junit5",
    "mockk-android",
    "turbine",
]
testing-jvm = [
    "junit5",
    "mockk",
    "turbine",
]

[plugins]
dependency-guard = { id = "com.dropbox.dependency-guard", version.ref = "dependency-guard" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
